services:

  db: 
    image: postgres_16
    environment:
      POSTGRESS_PASSWORD: dev
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready - U postgres"]
      interval: 5s
      timeout: 30s
      retries: 5
    
  backend:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:dev@db:5432/postgres
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
